services:
  - type: web
    name: investara-app
    env: python
    buildCommand: |
      pip install -r requirements.txt
    startCommand: |
      adk web
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
      - key: PORT
        value: 10000
    plan: free
    autoDeploy: true
