services:
  - type: web
    name: investara-app
    env: python
    buildCommand: |
      pip install -r requirements.txt
    rootDir: Agent_Kit
    startCommand: uvicorn nifty_agent.server:app --host 0.0.0.0 --port 10000
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
      - key: GOOGLE_GENAI_USE_VERTEXAI
        sync: false
      - key: PORT
        value: 10000
    plan: free
    autoDeploy: true
